modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
issueTrackerURL="https://github.com/aaronhowser1/LoFi-Records-To-Mine-To/issues" #optional
[[mods]] #mandatory
modId="lofirecordstomineto" #mandatory
version="${file.jarVersion}" #mandatory
displayName="LoFi Records to Mine To" #mandatory
updateJSONURL="http://myurl.me/" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/lofi-records-to-mine-to" #optional
logoFile="logo.png" #optional
credits="Music by 1micah5" #optional
authors="aaronhowser1, TheSilkMiner" #optional
description='''
Adds 31 Music Discs that play original tracks by 1micah5.

See more at https://soundcloud.com/lordmicah and https://tinyurl.com/rule5yt
'''
[[dependencies.lofirecordstomineto]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[35,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.lofirecordstomineto]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.0,)"
    ordering="NONE"
    side="BOTH"
